---

# which version?
java_version: 8

# which subversion?
java_subversion: 102

# which directory to put the download file?
java_download_path: /tmp

# rpm/tar.gz file location:
#   - true: download from Oracle on-the-fly;
#   - false: copy from `{{ playbook_dir }}/files` on the control machine.
java_download_from_oracle: true

# remove temporary downloaded files?
java_remove_download: true

# set $JAVA_HOME?
java_set_javahome: true

# install JCE?
java_install_jce: true

#JDK_home
jdk_home: "/usr/java/jdk1.{{ java_version }}.0_{{ java_subversion }}"